# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNBridgeTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNBridgeTest
  # Google AdMob tedt
  pod 'Google-Mobile-Ads-SDK'
  pod 'AppSamuraiAdSDK'
end
